name: Sepolia Gas Alert

on:
  # Manual trigger so you can press “Run workflow” right now
  workflow_dispatch:                    # :contentReference[oaicite:8]{index=8}
  # Scheduled trigger every 5 minutes
  schedule:
    - cron: '*/5 * * * *'               # shortest allowed interval :contentReference[oaicite:9]{index=9}

jobs:
  alert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install requests

      - run: python sepolia_gas_bot.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          ETHERSCAN_API_KEY:  ${{ secrets.ETHERSCAN_API_KEY }}
