name: Sepolia Gas Alert

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  alert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt    # installs python-dotenv + requests

      - name: Run bot script
        run: python sepolia_gas_bot.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          ETHERSCAN_API_KEY:  ${{ secrets.ETHERSCAN_API_KEY }}
